Repository jenkinsci/workflow-aggregator-plugin, pull requests merged in 2022-06, with the labels that each got.

#58 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#64 Pick up `pipeline-groovy-lib` from BOM
  pom.xml
Labels: dependencies

#65 Removing demo
  README.md
  clone-all
  demo/.gitignore
  demo/Dockerfile
  demo/JENKINS_HOME/config.xml
  demo/JENKINS_HOME/hudson.tasks.Maven.xml
  demo/JENKINS_HOME/jenkins.install.UpgradeWizard.state
  demo/JENKINS_HOME/jenkins.model.JenkinsLocationConfiguration.xml
  demo/JENKINS_HOME/jobs/cd/config.xml
  demo/JENKINS_HOME/log/Workflow.xml
  demo/JENKINS_HOME/maven-settings-files.xml
  demo/JENKINS_HOME/org.jenkinsci.main.modules.sshd.SSHD.xml
  demo/JENKINS_HOME/org.jenkinsci.plugins.workflow.libs.GlobalLibraries.xml
  demo/Makefile
  demo/README.md
  demo/globallib/vars/testResult.groovy
  demo/globallib/vars/testResult.txt
  demo/jetty.sh
  demo/lib/src/demo/Servers.groovy
  demo/lib/vars/mvn.groovy
  demo/lib/vars/mvn.txt
  demo/pom.xml
  demo/repo-branches/library-retriever.diff
  demo/repo-branches/library-step.diff
  demo/repo/Jenkinsfile
  demo/repo/pom.xml
  demo/repo/sometests/README.md
  demo/repo/sometests/pom.xml
  demo/repo/sometests/src/test/java/org/jenkinsci/plugins/workflow/demo/AppTest.java
  demo/repo/src/main/webapp/WEB-INF/web.xml
  demo/repo/src/main/webapp/index.jsp
  demo/run.sh
Labels: documentation

#66 Avoid `<groupId>${project.groupId}</groupId>` for deps
  pom.xml
Labels: developer
