Repository jenkinsci/workflow-aggregator-plugin, pull requests merged in 2022-05, with the labels that each got.

#47 remove lockable-resources dependency
  pom.xml
Labels: enhancement

#49 Link to GH Releases not manual changelog
  CHANGELOG.md
  README.md
Labels: documentation

#50 Update POM, use BOM, enable Dependabot
  .github/dependabot.yml
  Jenkinsfile
  pom.xml
Labels: dependencies

#51 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: developer

#52 [JENKINS-57023] Switch dep from `workflow-cps-global-lib` to `pipeline-groovy-lib`
  pom.xml
Labels: enhancement
